### PR TITLE
Fix `mergeStream.destroy()` logic

### LINKED ISSUE #20: Fix `mergeStream.destroy()` logic
Currently:
  - When all input streams end successfully (`stream.end()`), the merged stream ends successfully
  - When any input streams errors (`stream.destroy(error)`), the merged stream errors
  - When all input streams are aborted (`stream.destroy()`), the merged stream is aborted

Now, when some input streams are aborted and others end successfully, the merged stream is currently aborted. However, it should end successfully instead. Aborting a readable stream is not necessarily due to a bug or an error (see https://github.com/sindresorhus/execa/issues/824).

Let's take an example with Execa `childProcess.all` feature which combines `childProcess.stdout` and `childProcess.stderr` using `merge-streams`. If `childProcess.stdout` is piped to another process `stdin`, that other process might decide to terminate piping by calling `childProcess.stdout.destroy()`. When this happens, `childProcess.all` will not be aborted, if `childProcess.stderr` is still running.

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #20.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -80,16 +87,15 @@ class MergedStream extends PassThroughStream {
 
 const onMergedStreamFinished = async (passThroughStream, streams) => {
 	updateMaxListeners(passThroughStream, PASSTHROUGH_LISTENERS_COUNT);
-	const abortController = new AbortController();
-	try {
-		await Promise.race([
-			onMergedStreamEnd(passThroughStream, abortController),
-			onInputStreamsUnpipe(passThroughStream, streams, abortController),
-		]);
-	} finally {
```
Comment (ehmicky) [inline index.js:89]: `finally` not needed because this never throws.

File: index.js [hunk 2]
```diff
@@ -112,43 +118,51 @@ const validateStream = stream => {
...
-const endWhenStreamsDone = async ({passThroughStream, stream, streams, ended, onFinished}) => {
-	try {
-		const abortController = new AbortController();
-		try {
-			await Promise.race([
-				onFinished,
-				onInputStreamEnd({stream, streams, ended, abortController}),
-				onInputStreamUnpipe({passThroughStream, stream, streams, ended, abortController}),
-			]);
-		} finally {
```
Comment (ehmicky) [inline index.js:124]: `finally` not needed because this never throws.

File: index.js [hunk 3]
```diff
@@ -80,14 +87,15 @@ class MergedStream extends PassThroughStream {
 
 const onMergedStreamFinished = async (passThroughStream, streams) => {
 	updateMaxListeners(passThroughStream, PASSTHROUGH_LISTENERS_COUNT);
-	const abortController = new AbortController();
+	const controller = new AbortController();
+
 	try {
 		await Promise.race([
-			onMergedStreamEnd(passThroughStream, abortController),
```
Comment (ehmicky) [inline index.js:86]: Renamed to `controller` to avoid confusion with streams "abort", which are unrelated but share the same name.
