### PR TITLE
Fix using `.unpipe()`

### LINKED ISSUE #13: `stream.unpipe(mergedStream)` prevents the merged stream from completing
When one of the input streams is unpiped from the merged stream, the merged stream never completes.

```js
const inputStream = Readable.from(['.']);
const stream = mergeStreams([inputStream]);
inputStream.unpipe(stream);
await stream.toArray() // This never resolves
```

We should listen to the `unpipe` event, and mark unpiped streams as "complete".

See also https://github.com/grncdr/merge-stream/blob/a217797ff4a52581423ca1fc6eef409c4c992447/index.js#L14

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #13.

I have no additional pending PRs after this one, so we can make a patch release. :+1:

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -71,7 +72,25 @@ const onMergedStreamEnd = async (passThroughStream, {signal}) => {
...
 };
 
+const onInputStreamsUnpipe = async (streams, passThroughStream, {signal}) => {
+	const streamsSet = new Set(streams);
+	for await (const [stream] of on(passThroughStream, 'unpipe', {signal})) {
+		if (streamsSet.has(stream)) {
+			stream.emit(unpipeEvent);
+		}
+	}
+};
```
Comment (ehmicky) [inline index.js:93]: Unfortunately, the `unpipe` event is emitted only on the destination, not the source, so we need to do this.

File: index.js [hunk 2]
```diff
@@ -46,10 +46,11 @@ const getHighWaterMark = (streams, objectMode) => {
 const endWhenStreamsDone = async (passThroughStream, streams) => {
 	try {
 		const abortController = new AbortController();
-		setMaxListeners(streams.length + 1, abortController.signal);
+		setMaxListeners((streams.length * 2) + 2, abortController.signal);
```
Comment (sindresorhus) [inline index.js]: Would be good with a code comment about the magic numbers here.

**Review by sindresorhus — CHANGES_REQUESTED** [review]

File: index.js (hunk 2 above)
Comment (ehmicky) [reply index.js]: Done with 177ab80cb7e0cb6ae00b8556cd67119dfb86745a :+1:
